// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDytCSrNT6NbKdx7sNfVCixNnxJZ6aHRTM',
    appId: '1:442237537313:android:9b4c561485cb566143e760',
    messagingSenderId: '442237537313',
    projectId: 'ajeo-1be75',
    storageBucket: 'ajeo-1be75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsgZc8wHWYYA4UV8O0AAkA_V9n2YZrYkk',
    appId: '1:442237537313:ios:0d481dda9f366fc043e760',
    messagingSenderId: '442237537313',
    projectId: 'ajeo-1be75',
    storageBucket: 'ajeo-1be75.appspot.com',
    androidClientId: '442237537313-j5ddj5qpb3621sfrum9cpf54noaucdng.apps.googleusercontent.com',
    iosClientId: '442237537313-3mbkihhc4a15v9a4lda979h108nbm2re.apps.googleusercontent.com',
    iosBundleId: 'com.jideguru.flutterfireUiAuth',
  );
}
